# Generated by Django 6.0.4 on 2026-05-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='imagem',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
