# Generated by Django 6.0.4 on 2026-05-12 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clientprofile_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='imagem',
            field=models.ImageField(default='default.png', upload_to='profile_pics/'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('estado_conservacao', models.CharField(choices=[('Novo', 'Novo'), ('Usado', 'Usado'), ('Muito Usado', 'Muito Usado')], max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='capas_livros/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros_a_venda', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
            ],
        ),
    ]
