# Generated by Django 6.0.4 on 2026-05-20 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_avaliacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('livro', 'Livro'), ('perfil', 'Perfil')], max_length=20)),
                ('alvo_id', models.IntegerField()),
                ('alvo_nome', models.CharField(max_length=200)),
                ('motivo', models.CharField(choices=[('Fraude/Burla', 'Fraude/Burla'), ('Conteúdo Impróprio', 'Conteúdo Impróprio'), ('Preço Abusivo', 'Preço Abusivo'), ('Outro motivo', 'Outro motivo')], max_length=50)),
                ('descricao', models.TextField(blank=True, default='', max_length=500)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
