# Generated by Django 6.0.4 on 2026-05-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='avaliada',
            field=models.BooleanField(default=False),
        ),
    ]
